# Site settings
title: 문동준 CV
baseurl: "/Portfolio"
url: "https://mdj0126.github.io/"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Moon Dongjun
  desc: 게임 클라이언트 프로그래머 문동준입니다.
  email: ehdwns0126@naver.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance: 1
  bitbucket: 1
  dribbble: 1
  facebook: 1
  flickr: 1
  github: mdj0126
  google_plus: 1
  instagram: 1
  keybase: 1
  linkedin:  1
  pinterest: 1
  reddit: 1
  soundcloud: 1
  stack_exchange: 1
  steam: 1
  tumblr: 1
  gitlab: 1
  twitter: 1
  vimeo: 1
  wordpress: 1
  youtube: 1
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
